[workspace]
members  = ["ogg-batch-speedup", "audio-speedup", "xp3-audio-speedup", "xp3-pack-unpack"]
resolver = "2"

[profile.release]
lto       = true
opt-level = "z"
panic     = "abort"
strip     = true
