[package]
edition = "2024"
name    = "audio-speedup"
version = "0.1.0"

[dependencies]
anyhow            = "1.0"
clap              = { version = "4.5", features = ["derive"] }
log               = "0.4"
ogg-batch-speedup = { path = "../ogg-batch-speedup" }
pretty_env_logger = "0.5"
