[package]
edition = "2024"
name    = "xp3-pack-unpack"
version = "0.1.0"

[dependencies]
anyhow            = "1.0"
assert2           = "0.3"
clap              = { version = "4.5", features = ["derive"] }
log               = "0.4"
pretty_env_logger = "0.5"
xp3               = "0.3"
